//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMLToXYZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHSDepth
    {
        public int CHSDepthID { get; set; }
        public Nullable<int> CHSChartID { get; set; }
        public Nullable<double> LineValue { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Depth { get; set; }
    }
}
